spring:
    application:
        name: webrise

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/webrise
        username: webrise
        password: password
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:db/changelog/master.xml
        enabled: true
    docker:
      compose:
          enabled: true
          file: docker/docker-compose.yml

server:
    port: 8080