version: '3.8'
services:

  pg-main:
    container_name: pg-main
    image: postgres:14.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webrise
      POSTGRES_USER: webrise
      POSTGRES_PASSWORD: password
    restart: always
